include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_specify_types: true
    always_use_package_imports: true
    avoid_empty_else: true
    avoid_print: true
    avoid_catches_without_on_clauses: true
    avoid_final_parameters: true
    avoid_multiple_declarations_per_line: true
    prefer_is_not_empty: true
