name: boilerplate
description: A boilerplate project to make easier to setup a new project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  flutter_bloc: ^8.1.2
  flutter_flavorizr: ^2.1.5
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_svg: ^2.0.2
  fluttertoast: ^8.2.1
  get: ^4.6.5
  google_fonts: ^4.0.3
  hive_generator: ^2.0.0
  hive: ^2.2.3
  intl: ^0.18.0
  local_auth: ^2.1.6
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  share_plus: ^6.3.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flavorizr:
  flavors:
    dev:
      app:
        name: "boilerplate - dev"

      android:
        applicationId: "com.boilerplate.dev"

      ios:
        bundleId: "com.boilerplate.dev"

    hom:
      app:
        name: "boilerplate - hom"

      android:
        applicationId: "com.boilerplate.hom"

      ios:
        bundleId: "com.boilerplate.hom"

    prod:
      app:
        name: "boilerplate - prod"

      android:
        applicationId: "com.boilerplate"

      ios:
        bundleId: "com.boilerplate"
